### ISSUE TITLE
Rejoining games

### ISSUE THREAD

**Issue by ltiao** [lmccalman/spacerace#13]
Players who have already registered in the lobby and obtained a secret key should be able to rejoin games if they happen to drop out for some reason. @AlistaiReid suggested making secret key a hash or some function of MAC address

**Comment by hardbyte** [comment]
I don't think using the client's MAC address is a good idea. The client could be switching interfaces e.g., from WiFi to Ethernet, the same interface could also be running multiple clients.

What is the issue with using the server's generated auth token per client? Are you worried about generating fake secrets via collisions? If so instead of the current random 13 chars we could use a UUID.

What currently prevents clients from rejoining?

**Comment by AlistaiReid** [comment]
Clients can only rejoin if they remember their ID, but all our clients currently just get a new ID from the server. This means disconnecting leaves the old ship drifting, and if all players disconnect the game gets stuck until the map timeout. We either need to detect and remove unpiloted ships from the game (so it can return to lobby when everyone leaves), or  provide some way for the client to request a reproducible ID from the server so that you can tinker with your AI and rejoin without having to drop out of the race entirely.

**Comment by lmccalman** [comment]
I think the solution is to make clients give us the secret key rather than us generate it for them upon connection. If there's already a ship with that key (and name), then we assume it's a reconnection. Just don't share your secret key!!

**Comment by lmccalman** [comment]
I've pushed a first pass at this, seems to work.
